# Generated by Django 5.1.2 on 2024-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('cliente1_texto', models.TextField()),
                ('cliente1_nome', models.TextField()),
                ('cliente2_texto', models.TextField()),
                ('cliente2_nome', models.TextField()),
                ('cliente3_texto', models.TextField()),
                ('cliente3_nome', models.TextField()),
                ('cliente4_texto', models.TextField()),
                ('cliente4_nome', models.TextField()),
                ('cliente5_texto', models.TextField()),
                ('cliente5_nome', models.TextField()),
                ('cliente6_texto', models.TextField()),
                ('cliente6_nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContatoBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('whatsapp', models.TextField()),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('mapa_endereco1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaginaInicialBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducao_bg', models.ImageField(blank=True, upload_to='loriz')),
                ('projetos_bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaInicialImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos_imagem1', models.ImageField(blank=True, upload_to='loriz')),
                ('servicos_imagem2', models.ImageField(blank=True, upload_to='loriz')),
                ('servicos_imagem3', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaInicialTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_titulo', models.TextField()),
                ('inicio_descricao', models.TextField()),
                ('inicio_link', models.TextField()),
                ('servicos_titulo', models.TextField()),
                ('servico1_titulo', models.TextField()),
                ('servico1_descricao', models.TextField()),
                ('servico2_titulo', models.TextField()),
                ('servico2_descricao', models.TextField()),
                ('servico3_titulo', models.TextField()),
                ('servico3_descricao', models.TextField()),
                ('depoimento_titulo', models.TextField()),
                ('depoimento_texto', models.TextField()),
                ('depoimento_cliente', models.TextField()),
                ('depoimento_link', models.TextField()),
                ('projetos_titulo', models.TextField()),
                ('projetos_texto', models.TextField()),
                ('projetos_link', models.TextField()),
                ('mapa_endereco1', models.TextField()),
                ('mapa_endereco2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='loriz')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem1', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('projeto1', models.TextField()),
                ('projeto2', models.TextField()),
                ('projeto3', models.TextField()),
                ('projeto4', models.TextField()),
                ('projeto5', models.TextField()),
                ('projeto6', models.TextField()),
                ('projeto7', models.TextField()),
                ('projeto8', models.TextField()),
                ('projeto9', models.TextField()),
                ('projeto10', models.TextField()),
                ('projeto11', models.TextField()),
                ('projeto12', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicosBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ServicosImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem1', models.ImageField(blank=True, upload_to='loriz')),
                ('imagem2', models.ImageField(blank=True, upload_to='loriz')),
                ('imagem3', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='ServicosTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('servico1_titulo', models.TextField()),
                ('servico1_texto', models.TextField()),
                ('servico2_titulo', models.TextField()),
                ('servico2_texto', models.TextField()),
                ('servico3_titulo', models.TextField()),
                ('servico3_texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SobreBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='SobreImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem1', models.ImageField(blank=True, upload_to='loriz')),
                ('imagem2', models.ImageField(blank=True, upload_to='loriz')),
            ],
        ),
        migrations.CreateModel(
            name='SobreTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('texto', models.TextField()),
                ('frase1', models.TextField()),
                ('frase1_autor', models.TextField()),
                ('frase2', models.TextField()),
                ('frase2_autor', models.TextField()),
            ],
        ),
    ]
