# Generated by Django 5.1.2 on 2024-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loriz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem10',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem11',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem12',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem2',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem3',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem4',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem5',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem6',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem7',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem8',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
        migrations.AddField(
            model_name='projetosimagem',
            name='imagem9',
            field=models.ImageField(blank=True, upload_to='loriz'),
        ),
    ]
