# Generated by Django 5.1.2 on 2024-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loriz', '0002_projetosimagem_imagem10_projetosimagem_imagem11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatotexto',
            name='mapa_endereco2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
